"""Central geography reference data for GooCampus.

Single source of truth for the COUNTRY list used across the portal — the client
registration form's Academic "Country" dropdown AND the phone country-code
picker, plus the College module and partner forms (all read the `countries`
table, which app.py seeds from here at boot). States + cities live in their own
`states` / `cities` tables (Indian states); countries are global.

Each row: (name, iso2, dial_code, currency_code, region)
- dial_code includes the leading '+'.
- region is used only to group the phone-code dropdown into <optgroup>s.
India is pinned first in the UI regardless of alphabetical order.
"""

# Comprehensive list of sovereign states (+ a few common territories). Dial codes
# are ITU E.164. Kept broad on purpose — "full list", not just FMG destinations.
COUNTRIES = [
    ("India", "IN", "+91", "INR", "South Asia"),
    # ── South Asia ──
    ("Bangladesh", "BD", "+880", "BDT", "South Asia"),
    ("Bhutan", "BT", "+975", "BTN", "South Asia"),
    ("Maldives", "MV", "+960", "MVR", "South Asia"),
    ("Nepal", "NP", "+977", "NPR", "South Asia"),
    ("Pakistan", "PK", "+92", "PKR", "South Asia"),
    ("Sri Lanka", "LK", "+94", "LKR", "South Asia"),
    ("Afghanistan", "AF", "+93", "AFN", "South Asia"),
    # ── East & Southeast Asia ──
    ("China", "CN", "+86", "CNY", "East & Southeast Asia"),
    ("Hong Kong", "HK", "+852", "HKD", "East & Southeast Asia"),
    ("Macau", "MO", "+853", "MOP", "East & Southeast Asia"),
    ("Taiwan", "TW", "+886", "TWD", "East & Southeast Asia"),
    ("Japan", "JP", "+81", "JPY", "East & Southeast Asia"),
    ("South Korea", "KR", "+82", "KRW", "East & Southeast Asia"),
    ("North Korea", "KP", "+850", "KPW", "East & Southeast Asia"),
    ("Mongolia", "MN", "+976", "MNT", "East & Southeast Asia"),
    ("Indonesia", "ID", "+62", "IDR", "East & Southeast Asia"),
    ("Malaysia", "MY", "+60", "MYR", "East & Southeast Asia"),
    ("Singapore", "SG", "+65", "SGD", "East & Southeast Asia"),
    ("Thailand", "TH", "+66", "THB", "East & Southeast Asia"),
    ("Vietnam", "VN", "+84", "VND", "East & Southeast Asia"),
    ("Philippines", "PH", "+63", "PHP", "East & Southeast Asia"),
    ("Myanmar", "MM", "+95", "MMK", "East & Southeast Asia"),
    ("Cambodia", "KH", "+855", "KHR", "East & Southeast Asia"),
    ("Laos", "LA", "+856", "LAK", "East & Southeast Asia"),
    ("Brunei", "BN", "+673", "BND", "East & Southeast Asia"),
    ("Timor-Leste", "TL", "+670", "USD", "East & Southeast Asia"),
    # ── Central Asia & CIS ──
    ("Kazakhstan", "KZ", "+7", "KZT", "Central Asia & CIS"),
    ("Kyrgyzstan", "KG", "+996", "KGS", "Central Asia & CIS"),
    ("Tajikistan", "TJ", "+992", "TJS", "Central Asia & CIS"),
    ("Turkmenistan", "TM", "+993", "TMT", "Central Asia & CIS"),
    ("Uzbekistan", "UZ", "+998", "UZS", "Central Asia & CIS"),
    ("Russia", "RU", "+7", "RUB", "Central Asia & CIS"),
    ("Ukraine", "UA", "+380", "UAH", "Central Asia & CIS"),
    ("Belarus", "BY", "+375", "BYN", "Central Asia & CIS"),
    ("Armenia", "AM", "+374", "AMD", "Central Asia & CIS"),
    ("Azerbaijan", "AZ", "+994", "AZN", "Central Asia & CIS"),
    ("Georgia", "GE", "+995", "GEL", "Central Asia & CIS"),
    ("Moldova", "MD", "+373", "MDL", "Central Asia & CIS"),
    # ── Middle East ──
    ("United Arab Emirates", "AE", "+971", "AED", "Middle East"),
    ("Saudi Arabia", "SA", "+966", "SAR", "Middle East"),
    ("Qatar", "QA", "+974", "QAR", "Middle East"),
    ("Kuwait", "KW", "+965", "KWD", "Middle East"),
    ("Oman", "OM", "+968", "OMR", "Middle East"),
    ("Bahrain", "BH", "+973", "BHD", "Middle East"),
    ("Jordan", "JO", "+962", "JOD", "Middle East"),
    ("Lebanon", "LB", "+961", "LBP", "Middle East"),
    ("Israel", "IL", "+972", "ILS", "Middle East"),
    ("Palestine", "PS", "+970", "ILS", "Middle East"),
    ("Iraq", "IQ", "+964", "IQD", "Middle East"),
    ("Iran", "IR", "+98", "IRR", "Middle East"),
    ("Syria", "SY", "+963", "SYP", "Middle East"),
    ("Yemen", "YE", "+967", "YER", "Middle East"),
    ("Turkey", "TR", "+90", "TRY", "Middle East"),
    # ── Europe ──
    ("United Kingdom", "GB", "+44", "GBP", "Europe"),
    ("Ireland", "IE", "+353", "EUR", "Europe"),
    ("Germany", "DE", "+49", "EUR", "Europe"),
    ("France", "FR", "+33", "EUR", "Europe"),
    ("Italy", "IT", "+39", "EUR", "Europe"),
    ("Spain", "ES", "+34", "EUR", "Europe"),
    ("Portugal", "PT", "+351", "EUR", "Europe"),
    ("Netherlands", "NL", "+31", "EUR", "Europe"),
    ("Belgium", "BE", "+32", "EUR", "Europe"),
    ("Luxembourg", "LU", "+352", "EUR", "Europe"),
    ("Switzerland", "CH", "+41", "CHF", "Europe"),
    ("Austria", "AT", "+43", "EUR", "Europe"),
    ("Sweden", "SE", "+46", "SEK", "Europe"),
    ("Norway", "NO", "+47", "NOK", "Europe"),
    ("Denmark", "DK", "+45", "DKK", "Europe"),
    ("Finland", "FI", "+358", "EUR", "Europe"),
    ("Iceland", "IS", "+354", "ISK", "Europe"),
    ("Poland", "PL", "+48", "PLN", "Europe"),
    ("Czech Republic", "CZ", "+420", "CZK", "Europe"),
    ("Slovakia", "SK", "+421", "EUR", "Europe"),
    ("Hungary", "HU", "+36", "HUF", "Europe"),
    ("Romania", "RO", "+40", "RON", "Europe"),
    ("Bulgaria", "BG", "+359", "BGN", "Europe"),
    ("Greece", "GR", "+30", "EUR", "Europe"),
    ("Croatia", "HR", "+385", "EUR", "Europe"),
    ("Slovenia", "SI", "+386", "EUR", "Europe"),
    ("Serbia", "RS", "+381", "RSD", "Europe"),
    ("Bosnia and Herzegovina", "BA", "+387", "BAM", "Europe"),
    ("North Macedonia", "MK", "+389", "MKD", "Europe"),
    ("Albania", "AL", "+355", "ALL", "Europe"),
    ("Montenegro", "ME", "+382", "EUR", "Europe"),
    ("Kosovo", "XK", "+383", "EUR", "Europe"),
    ("Estonia", "EE", "+372", "EUR", "Europe"),
    ("Latvia", "LV", "+371", "EUR", "Europe"),
    ("Lithuania", "LT", "+370", "EUR", "Europe"),
    ("Cyprus", "CY", "+357", "EUR", "Europe"),
    ("Malta", "MT", "+356", "EUR", "Europe"),
    # ── North America ──
    ("United States", "US", "+1", "USD", "North America"),
    ("Canada", "CA", "+1", "CAD", "North America"),
    ("Mexico", "MX", "+52", "MXN", "North America"),
    # ── Latin America & Caribbean ──
    ("Brazil", "BR", "+55", "BRL", "Latin America & Caribbean"),
    ("Argentina", "AR", "+54", "ARS", "Latin America & Caribbean"),
    ("Chile", "CL", "+56", "CLP", "Latin America & Caribbean"),
    ("Colombia", "CO", "+57", "COP", "Latin America & Caribbean"),
    ("Peru", "PE", "+51", "PEN", "Latin America & Caribbean"),
    ("Venezuela", "VE", "+58", "VES", "Latin America & Caribbean"),
    ("Ecuador", "EC", "+593", "USD", "Latin America & Caribbean"),
    ("Bolivia", "BO", "+591", "BOB", "Latin America & Caribbean"),
    ("Paraguay", "PY", "+595", "PYG", "Latin America & Caribbean"),
    ("Uruguay", "UY", "+598", "UYU", "Latin America & Caribbean"),
    ("Guyana", "GY", "+592", "GYD", "Latin America & Caribbean"),
    ("Suriname", "SR", "+597", "SRD", "Latin America & Caribbean"),
    ("Panama", "PA", "+507", "PAB", "Latin America & Caribbean"),
    ("Costa Rica", "CR", "+506", "CRC", "Latin America & Caribbean"),
    ("Guatemala", "GT", "+502", "GTQ", "Latin America & Caribbean"),
    ("Honduras", "HN", "+504", "HNL", "Latin America & Caribbean"),
    ("El Salvador", "SV", "+503", "USD", "Latin America & Caribbean"),
    ("Nicaragua", "NI", "+505", "NIO", "Latin America & Caribbean"),
    ("Cuba", "CU", "+53", "CUP", "Latin America & Caribbean"),
    ("Dominican Republic", "DO", "+1809", "DOP", "Latin America & Caribbean"),
    ("Haiti", "HT", "+509", "HTG", "Latin America & Caribbean"),
    ("Jamaica", "JM", "+1876", "JMD", "Latin America & Caribbean"),
    ("Trinidad and Tobago", "TT", "+1868", "TTD", "Latin America & Caribbean"),
    ("Barbados", "BB", "+1246", "BBD", "Latin America & Caribbean"),
    ("Bahamas", "BS", "+1242", "BSD", "Latin America & Caribbean"),
    ("Grenada", "GD", "+1473", "XCD", "Latin America & Caribbean"),
    ("Saint Lucia", "LC", "+1758", "XCD", "Latin America & Caribbean"),
    ("Antigua and Barbuda", "AG", "+1268", "XCD", "Latin America & Caribbean"),
    # ── Africa ──
    ("Nigeria", "NG", "+234", "NGN", "Africa"),
    ("Ghana", "GH", "+233", "GHS", "Africa"),
    ("Kenya", "KE", "+254", "KES", "Africa"),
    ("Tanzania", "TZ", "+255", "TZS", "Africa"),
    ("Uganda", "UG", "+256", "UGX", "Africa"),
    ("Ethiopia", "ET", "+251", "ETB", "Africa"),
    ("Rwanda", "RW", "+250", "RWF", "Africa"),
    ("South Africa", "ZA", "+27", "ZAR", "Africa"),
    ("Zambia", "ZM", "+260", "ZMW", "Africa"),
    ("Zimbabwe", "ZW", "+263", "ZWL", "Africa"),
    ("Botswana", "BW", "+267", "BWP", "Africa"),
    ("Namibia", "NA", "+264", "NAD", "Africa"),
    ("Mozambique", "MZ", "+258", "MZN", "Africa"),
    ("Egypt", "EG", "+20", "EGP", "Africa"),
    ("Morocco", "MA", "+212", "MAD", "Africa"),
    ("Algeria", "DZ", "+213", "DZD", "Africa"),
    ("Tunisia", "TN", "+216", "TND", "Africa"),
    ("Libya", "LY", "+218", "LYD", "Africa"),
    ("Sudan", "SD", "+249", "SDG", "Africa"),
    ("Senegal", "SN", "+221", "XOF", "Africa"),
    ("Ivory Coast", "CI", "+225", "XOF", "Africa"),
    ("Cameroon", "CM", "+237", "XAF", "Africa"),
    ("Mauritius", "MU", "+230", "MUR", "Africa"),
    ("Angola", "AO", "+244", "AOA", "Africa"),
    ("Democratic Republic of the Congo", "CD", "+243", "CDF", "Africa"),
    # ── Oceania ──
    ("Australia", "AU", "+61", "AUD", "Oceania"),
    ("New Zealand", "NZ", "+64", "NZD", "Oceania"),
    ("Fiji", "FJ", "+679", "FJD", "Oceania"),
    ("Papua New Guinea", "PG", "+675", "PGK", "Oceania"),
    # ── Other ──
    ("Other", "", "", "USD", "Other"),
]

# Region order for grouping the phone-code dropdown (India pinned first separately).
REGION_ORDER = [
    "South Asia", "East & Southeast Asia", "Central Asia & CIS", "Middle East",
    "Europe", "North America", "Latin America & Caribbean", "Africa", "Oceania", "Other",
]
